from typing import NoReturn, Callable, Union

from PyQt5.QtCore import QObject, pyqtSignal

from gui.file_managment.files_list import FilesList
from storage.loader import Loader
from storage.slot import Slot
from storage.table_controller import TableController, InputEntity, FileDialogInput, DragAndDropInput


class Storage(QObject):
    __list: ListWithCallbacks = ...
    __loader: Loader = ...
    __controller: TableController = ...

    __set_empty_signal: pyqtSignal = ...
    __set_workspace_signal: pyqtSignal = ...

    def __init__(self, files_list_widget:FilesList, set_empty_callback: Callable[[], NoReturn],
                 set_workspace_callback: Callable[[], NoReturn]) -> NoReturn: ...

    def add(self, input: Union[InputEntity, FileDialogInput, DragAndDropInput]) -> NoReturn: ...

    def __store_slot(self, slot: Slot) -> NoReturn: ...

    def get(self, y: int) -> Slot: ...


class ListWithCallbacks(list):
    __set_empty_callback: Callable[[], NoReturn] = ...
    __set_workspace_callback: Callable[[], NoReturn] = ...

    def __init__(self, set_empty_callback: Callable[[], NoReturn], set_workspace_callback: Callable[[], NoReturn]): ...

    def append(self, __object: Slot) -> NoReturn: ...

    def pop(self, __index: int) -> Slot: ...
